### ISSUE TITLE
Issued date is after the modification date?

### ISSUE THREAD

**Issue by gatemezing** [core-o/ontology#1]
Hello @rfcalhau ,
First issued date vs last Modified date.
According to LOV Bot, the modification date is before the first issued date? (April vs May)?
I also suggest to use a date type for `dcterms:modified`
```
<http://purl.org/dc/terms/issued> "2023-05-08"^^xsd:date ;
                         <http://purl.org/dc/terms/license> "https://creativecommons.org/licenses/by/4.0/legalcode"^^xsd:anyURI ;
                         <http://purl.org/dc/terms/modified> "2023-04-08"^^xsd:date
``` 

Is that correct?
Best,

**Comment by jpalmeida** [comment]
Thanks a lot.
